name: Run Behave Tests

# Trigger the workflow on push to the 'main' branch or when a pull request is made
on:
  push:
    branches:
      - main    # or 'master' based on your default branch
  pull_request:
    branches:
      - main    # or 'master'

jobs:
  test:
    # The environment the tests will run on
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python (use the Python version your project needs)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'   # Modify this based on the version your project needs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # Ensure you have all your dependencies in requirements.txt

      # Step 4: Run Behave Tests
      - name: Run Behave tests
        run: |
          behave --tags=api_test  # Optional: You can specify a tag to only run specific tests

      # Step 5: (Optional) Upload Allure report as an artifact (if using Allure)
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-results/

